### PR TITLE
Integrate BTC in the bookmarks page - Close #647

### LINKED ISSUE #647: Refactor Bookmarks feature to work properly with other tokens
### Description
The current state of the Bookmarks feature doesn't block us to use it for the other tokens. 

However, we may need a filtering logic to retrieve related addresses which is compatible with the active token in Redux store.

*Changes required*
- Refactor the account reducers and actions to allow multiple tokens.
- Refactor the storage utility to store and retrieve folloed accounts/bookmarks with multiple tokens.
- The storage utility must normalize the retrived data to ensure the app won’t crash in case users have old bookmarks stored.
- The page/component must load bookmarks according to the active-token selection.
- We shouldn’t show avatar for BTC accounts.

### PR DESCRIPTION
**Pull request by yasharAyari**
# What was the bug or feature?
It is described in #647.

## Type of change
- Enhancement (a non-breaking change which adds functionality)

### How to test it?
Try to add different items to the bookmark list of different tokens. Then you must see a different list for each token.

# Checklist:
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented on my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/store/reducers/accounts.js [hunk 1]
```diff
@@ -41,20 +43,40 @@ const accounts = (state = INITIAL_STATE, action = {}) => {
...
 
-    case actionTypes.accountEdited:
+    case actionTypes.accountEdited: {
+      const { account, activeToken } = action.data;
       return merge(state, {
-        followed: state.followed.map(i => (i.address === action.data.address ? action.data : i)),
+        followed: tokenKeys.reduce((info, tokenKey) => merge(info, {
+          [tokenKey]: tokenKey === activeToken ?
+            [
+              ...state.followed[tokenKey]
```
Comment (aydieneue) [inline src/store/reducers/accounts.js]: Sorry, I couldn't follow the direct usage of `...` in `[]` here. Seems extra to me 🤔

Screenshot 2019-03-20 at 14 05 24

File: src/store/reducers/accounts.js [hunk 2]
```diff
@@ -41,20 +43,40 @@ const accounts = (state = INITIAL_STATE, action = {}) => {
...
-    case actionTypes.accountFollowed:
+    case actionTypes.accountFollowed: {
+      const { account, activeToken } = action.data;
       return merge(state, {
-        followed: [...state.followed.filter(item =>
-          item.address !== action.data.address), action.data],
+        followed: tokenKeys.reduce((info, tokenKey) => merge(info, {
+          [tokenKey]: tokenKey === activeToken ?
+            [
+              ...state.followed[tokenKey]
```
Comment (aydieneue) [inline src/store/reducers/accounts.js]: This is 👌 for concatting with the `account` ✅

File: src/store/reducers/accounts.js [hunk 3]
```diff
@@ -41,20 +43,40 @@ const accounts = (state = INITIAL_STATE, action = {}) => {
...
+        }), {}),
       });
+    }
 
     case actionTypes.accountUnFollowed:
       return merge(state, {
-        followed: [...state.followed.filter(item => item.address !== action.data)],
+        followed: tokenKeys.reduce((info, tokenKey) => merge(info, {
+          [tokenKey]: tokenKey === action.data.activeToken ?
+            [...state.followed[tokenKey].filter(item => item.address !== action.data.address)] :
```
Comment (aydieneue) [inline src/store/reducers/accounts.js]: Same as the direct return

Screenshot 2019-03-20 at 14 05 24

File: src/components/wallet/index.js [hunk 4]
```diff
@@ -73,7 +73,7 @@ class Wallet extends React.Component {
     const {
       activeToken, navigation: { setParams }, followedAccounts,
     } = this.props;
-    const storedAccount = followedAccounts.filter(item =>
+    const storedAccount = followedAccounts[activeToken].filter(item =>
```
[the remark this answers is not in the document]
Comment (yasharAyari) [reply src/components/wallet/index.js]: please create another an issue for the enhancement that you asked. Because the change you asked is out of the context of this issue.

File: src/store/reducers/accounts.js (hunk 2 above)
Comment (yasharAyari) [reply src/store/reducers/accounts.js]: It actually adds the account that you want to add into the current list of fallowed accounts.

File: src/components/wallet/index.js [hunk 5]
```diff
@@ -168,9 +168,10 @@ class Wallet extends React.Component {
   }
 
   componentDidUpdate(prevProps, prevState) {
```
[the remark this answers is not in the document]
Comment (yasharAyari) [reply src/components/wallet/index.js]: please create another an issue for the enhancement that you asked. Because the change you asked is out of the context of this issue.

File: src/components/addBookmark/index.js [hunk 6]
```diff
@@ -182,12 +187,27 @@ class AddToBookmark extends React.Component {
...
-      navigation, theme, styles, t, lng,
+      navigation, theme, styles, t, lng, activeToken,
     } = this.props;
     const {
       address, avatarPreview, label, incomingData, editMode,
     } = this.state;
 
+    const shouldDisplayAvatar = activeToken === tokenMap.LSK.key;
+
+    const renderAvatar = () => (avatarPreview ?
```
Comment (aydieneue) [inline src/components/addBookmark/index.js]: @yasharAyari @reyraa I am not sure about having this function here. 

Waiting for a proper feedback on this ->
https://github.com/LiskHQ/lisk-mobile/blob/661-send-recipient-validation/src/components/send/recipient/index.js#L169-L185

which was the end result of this discussion -> https://github.com/LiskHQ/lisk-mobile/pull/662#pullrequestreview-216662288
