### PR TITLE
Broken screen styles - Closes #1145, #1144, #1142

### LINKED ISSUE #1145: Button overlays on message input field
### Expected behavior
When the keyboard is open, the Continue button should not overlay on the Message Input field

### Actual behavior
Continue button currently overlays on message input field

### Steps to reproduce
On the send LSK screen, Select Add Message and focus on the message input field

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0-alpha.0
Screenshot 2021-11-25 at 13 17 42

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1145 #1144 #1142 

### How was it solved?
Re-implemented designs to match proposed designs

### How was it tested?
iOS and android simulator and iPhone 12 Pro (device)

https://user-images.githubusercontent.com/28750984/143459300-fd63e302-6303-44dd-8cf9-b5f8d0af505c.mp4

https://user-images.githubusercontent.com/28750984/143459330-137cedda-a401-4f67-9ceb-69f55a314b2b.mp4

### CODE REVIEW

File: src/components/screens/wallet/index.js [hunk 1]
```diff
@@ -241,15 +242,35 @@ class Wallet extends React.Component {
...
       <View style={[styles.container, styles.theme.container]}>
-        {account && account.address ? (
-          <AccountSummary
+        <ParallaxHeader
+          headerMinHeight={70}
+          headerMaxHeight={220}
+          extraScrollHeight={20}
+          navbarColor="#3498db"
+          alwaysShowTitle={false}
+          // refreshControl={
```
Comment (ManuGowda) [inline src/components/screens/wallet/index.js:251]: why commented?

File: src/components/screens/wallet/index.js [hunk 2]
```diff
@@ -241,15 +242,35 @@ class Wallet extends React.Component {
...
             scrollY={this.scrollY}
             account={account}
             style={styles.accountSummary}
-          />
-        ) : null}
-        {content}
+          />}
+          renderContent={() => content}
+          scrollViewProps={{
+            // onScroll: this.onScroll
```
Comment (ManuGowda) [inline src/components/screens/wallet/index.js:271]: same here

**Review by ManuGowda — APPROVED** [review]

File: src/components/screens/wallet/index.js (hunk 1 above)
Comment (Balanced02) [reply src/components/screens/wallet/index.js]: Fixed now.

Forgot to push my changes. 
@ManuGowda
