### PR TITLE
Remove Choose from Bookmark on send screen with no bookmarked list

### LINKED ISSUE #1549: Choose from bookmark should only be visible when users have bookmarked addresses
### Expected behavior
- Should show choose from bookmark on the send token screen only when users have at least one address bookmarked

### Actual behavior
- Shows choose from bookmark button even if users doesn't have any bookmarked address

### Steps to reproduce
Simulator Screen Shot - iPhone 14 Pro - 2022-12-07 at 16 25 37

### Which version(s) does this affect? (Environment, OS, etc...)
- v3.0.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?

This PR resolves #1549 

### How was it solved?
- [x] Check for bookmark list before rendering 'choose from bookmark` component
- [x] Fixed empty illustration state for bookmark list

### How was it tested?
- [x] Android device
- [x] iOS Simulator

### CODE REVIEW

File: src/modules/Bookmark/AddBookmark/index.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default function AddBookmark({ route }) {
 
   const { styles } = useTheme({ styles: getStyles() });
 
-  const [address, setAddress] = useState({ value: '' });
+  const [address, setAddress] = useState({ value: 'lskqzpfr3uq8bm2jee5dkv4ns79uuswjzc9bbpezu' });
```
Comment (ClementeSerrano) [inline src/modules/Bookmark/AddBookmark/index.js:36]: you missed this hardcoded value :)

**Review by ClementeSerrano — CHANGES_REQUESTED** [review]

**Review by ClementeSerrano — APPROVED** [review]
