### PR TITLE
Fix app crashes when transaction amounts are decimal

### LINKED ISSUE #1989: App crashes when transaction amounts are decimal
### Expected behavior

Ensure both send and request form handles the following:

- Handle decimal conversions based on token metadata and its decimals
- Show error when decimals points are greater than supported

### Actual behavior
For amounts like `0.000000000001 LSK`, or `0.123456789` the app is crashing.

### Steps to reproduce
1. Login to an account with balance.
2. Go to the send token form.
3. In the second step, enter a long decimal amount, like `0.000000000001` or `0.123456789`.
4. You will see the app crashing.

This is breaking changes, it was fixed in https://github.com/LiskHQ/lisk-mobile/issues/1770

### Which version(s) does this affect? (Environment, OS, etc...)
All

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?

This PR resolves #1989 

### How was it solved?
- Used a try-catch block to catch error

### How was it tested?
- iOS Simulator

https://github.com/LiskHQ/lisk-mobile/assets/28750984/3b69043a-bd2a-4323-81db-95031ac7a996

https://github.com/LiskHQ/lisk-mobile/assets/28750984/02686182-4742-4a70-9f8c-8bdcd23af1c3

### CODE REVIEW

File: src/modules/RequestToken/hook/useRequestTokenAmountValidation.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
+/* eslint-disable max-statements */
```
Comment (ManuGowda) [inline src/modules/RequestToken/hook/useRequestTokenAmountValidation.js:1]: do you need this lint?

File: src/modules/RequestToken/hook/useRequestTokenAmountValidation.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+import { useApplicationSupportedTokensQuery } from 'modules/BlockchainApplication/api/useApplicationSupportedTokensQuery';
+import { fromDisplayToBaseDenom } from 'utilities/conversions.utils';
+import { validateTransactionAmount } from 'utilities/validators';
+
+export function useRequestTokenAmountValidation({ recipientApplication, selectedTokenID, amount }) {
+  const { data: supportedTokensData } = useApplicationSupportedTokensQuery(recipientApplication);
+
+  const selectedToken = supportedTokensData?.find((token) => token.tokenID === selectedTokenID);
+
+  let isValid = true;
```
Comment (ManuGowda) [inline src/modules/RequestToken/hook/useRequestTokenAmountValidation.js:11]: isAmountValid?

**Review by ManuGowda — APPROVED** [review]
