### PR TITLE
Fix animation glitch in Transaction Detail - Closes #1297

### LINKED ISSUE #1297: Page navigation transition glitch
### Expected behavior
The account details page goes down below the transaction details header before the swipe animation, causing the animation to be not smooth. (Shown at 5th and 28th second of the video below)

### Actual behavior
https://user-images.githubusercontent.com/25085095/155330907-46b2be32-834b-4bf7-aa0e-e99c503e4781.MOV

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1297 

### How was it solved?
- Refactor header for Transaction Detail to allow header and screen transition together

### How was it tested?
iOS and Android emulators

### CODE REVIEW

File: src/components/screens/txDetail/index.js [hunk 1]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
+                  value={tx.senderAddress}
+                  onPress={() => goToWallet(tx.recipientAddress, this.props)}
+                  style={[styles.value, styles.theme.value, styles.transactionId]}
+                >
+                  {getAccountLabel(tx.recipientAddress, { ...this.props, truncate: true })}
+                </A>
+              </View>
+              <Avatar address={config.secondAddress} size={40} />
+            </Row>
+          )}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:227]:
```suggestion
          {!isTransfer(tx) || tx.recipientAddress === tx.senderAddress && (
            <Row title="Recipient">
              <View style={styles.addressContainer}>
                <A
                  value={tx.senderAddress}
                  onPress={() => goToWallet(tx.recipientAddress, this.props)}
                  style={[styles.value, styles.theme.value, styles.transactionId]}
                >
                  {getAccountLabel(tx.recipientAddress, { ...this.props, truncate: true })}
                </A>
              </View>
              <Avatar address={config.secondAddress} size={40} />
            </Row>
          )}
```

File: src/components/screens/txDetail/index.js [hunk 2]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
+            {!incognito ? (
+              <H4 style={config.amountStyle}>
+                {config.amountSign}
+                <FormattedNumber language={language}>{fromRawLsk(tx.amount)}</FormattedNumber>
+              </H4>
+            ) : null}
+            {incognito ? (
+              <Blur value={amount} direction={config.direction} />
+            ) : null}
+          </Row>}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:238]:
```suggestion
            {!incognito ? (
              <H4 style={config.amountStyle}>
                {config.amountSign}
                <FormattedNumber language={language}>{fromRawLsk(tx.amount)}</FormattedNumber>
              </H4>
            ) :  (
              <Blur value={amount} direction={config.direction} />
            ) 
          </Row>}
```

File: src/components/screens/txDetail/index.js [hunk 3]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
+          {!isUnlock(tx) ? null : (
+            <Row title="Amount">
+              <B style={[styles.value, styles.theme.value]}>
+                <FormattedNumber tokenType={activeToken} language={language}>
+                  {fromRawLsk(tx.amount)}
+                </FormattedNumber>
+              </B>
+            </Row>
+          )}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:247]:
```suggestion
          {!isUnlock(tx) && (
            <Row title="Amount">
              <B style={[styles.value, styles.theme.value]}>
                <FormattedNumber tokenType={activeToken} language={language}>
                  {fromRawLsk(tx.amount)}
                </FormattedNumber>
              </B>
            </Row>
          )}
```

File: src/components/screens/txDetail/index.js [hunk 4]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
+              <B style={[styles.value, styles.theme.value, styles.referenceValue]}>{tx.data}</B>
+            </Row>
+          ) : null}
+          {tx.confirmations ? (
+            <Row title="Confirmations">
+              <B style={[styles.value, styles.theme.value, styles.referenceValue]}>
+                {tx.confirmations}
+              </B>
+            </Row>
+          ) : null}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:266]:
```suggestion
          {!!tx.data && (
            <Row title="Message">
              <B style={[styles.value, styles.theme.value, styles.referenceValue]}>{tx.data}</B>
            </Row>
          )}
          {!!tx.confirmations && (
            <Row title="Confirmations">
              <B style={[styles.value, styles.theme.value, styles.referenceValue]}>
                {tx.confirmations}
              </B>
            </Row>
          ) }
```

File: src/components/screens/txDetail/index.js [hunk 5]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
-        </Row>
-        {tx.blockHeight ? (
-          <Row title="Block Height">
+          {tx.blockHeight ? (
+            <Row title="Block Height">
+              <B style={[styles.value, styles.theme.value]}>
+                {tx.blockHeight}
+              </B>
+            </Row>
+          ) : null}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:293]:
```suggestion
          {!!tx.blockHeight && (
            <Row title="Block Height">
              <B style={[styles.value, styles.theme.value]}>
                {tx.blockHeight}
              </B>
            </Row>
          ) }
```

File: src/components/screens/txDetail/index.js [hunk 6]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
+                style={[styles.value, styles.theme.value, styles.transactionId]}
+                labelStyle={[styles.value, styles.theme.value]}
+                showIcon={true}
+                iconSize={18}
+                value={tx.blockId}
+                type={B}
+                label={stringShortener(tx.blockId, 15, 6)}
+              />
+            </Row>
+          ) : null}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:306]:
```suggestion
          {!!tx.blockId && (
            <Row title="Block ID">
              <CopyToClipboard
                style={[styles.value, styles.theme.value, styles.transactionId]}
                labelStyle={[styles.value, styles.theme.value]}
                showIcon={true}
                iconSize={18}
                value={tx.blockId}
                type={B}
                label={stringShortener(tx.blockId, 15, 6)}
              />
            </Row>
          ) }
```

File: src/components/screens/txDetail/index.js [hunk 7]
```diff
@@ -171,147 +165,153 @@ class TransactionDetail extends React.Component {
...
-          </Row>
-        ) : null}
-        <Row title={'Nonce'}>
-          <B style={[styles.value, styles.theme.value]}>
-            {tx.nonce}
-          </B>
-        </Row>
-        {isVoting ? <VoteList votes={votes} /> : null}
-      </ScrollView>
+          {isVoting ? <VoteList votes={votes} /> : null}
```
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:312]:
```suggestion
          {isVoting && <VoteList votes={votes} /> }
```

File: src/components/screens/txDetail/index.js (hunk 5 above)
Comment (eniolam1000752) [inline src/components/screens/txDetail/index.js:293]:
```suggestion
          {!!tx.blockHeight && (
            <Row title="Block Height">
              <B style={[styles.value, styles.theme.value]}>
                {tx.blockHeight}
              </B>
            </Row>
          ) }
```

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]
Functionally okay

**Review by eniolam1000752 — APPROVED** [review]
