### PR TITLE
iMessage app does not open received request templates - Closes #1004

### LINKED ISSUE #1004: iMessage app doesn't open received request templates
**To Reproduce**
 - Ask someone to request LSK through iMessage.
 - Tap on the received request. 

**Actual behavior**
The screen opens white with a loader spinner and nothing else happens.

**Expected behavior**
Should open an interface enabling me to approve or reject the request.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.1.2
 - Version 1.3.0

### PR DESCRIPTION
**Pull request by RaquelCasadoDias**
# What was the bug or feature?
It is described at #1004.

### How did I fix it?
Refactored formattedNumber component, which doesn't access store anymore, instead it receives the value of language through props.

## Type of change
- Bug fix (a non-breaking change which fixes an issue)

### How to test it?

**For the bug:**
- Open iMessage extension, send a request to someone. (Do it in the simulator, so you can send the request and access it from the same device)
- Open the message from the recipient. A window should pop up with transaction details.

**For the refactor:**
- Go to any screen that uses formattedNumber, those being: profile, send (the whole flow), transaction detail, accountSummary and transactions.
- Just make  the screen loads normally and values are formatted as they should. 

# Checklist:
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/shared/formattedNumber/index.js [hunk 1]
```diff
@@ -1,24 +1,13 @@
...
-      val,
-      children,
-      type,
-      style,
-      trim,
-      tokenType,
-      language,
-    } = this.props;
+    const { val, children, type, style, trim, tokenType } = this.props;
+    const language = 'en';
```
Comment (colado) [inline src/components/shared/formattedNumber/index.js]: 💅 Better to take the `const` from here: https://github.com/LiskHQ/lisk-mobile/blob/76f354ae86c7f1c4dea9a2e9cdc77f5703e03018/src/constants/languages.js#L5
