### PR TITLE
Fix biometrics flow and disable multisignature to send token

### LINKED ISSUE #1982: Face ID verification issues on iOS
### Expected behavior
Face ID should behave as expected when it comes to authentication requests.

### Actual behavior
There are several issues happening with Face ID requests:

1. Face ID verification for token:transfer sometimes work and sometimes not.

https://github.com/LiskHQ/lisk-mobile/assets/9727036/721bdd84-47e8-41bc-83a8-e16a7c453baa

2.  FaceID check runs too many times. At least twice when activating/deactivating it.

https://github.com/LiskHQ/lisk-mobile/assets/9727036/721504f5-6fc6-4d36-81c2-e9918e8df917

3. Deactivated FaceID stills asking for verification.

https://github.com/LiskHQ/lisk-mobile/assets/9727036/6022385a-9746-4681-a7c1-0c1f4d7f9250

### Steps to reproduce
See videos above.

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?

This PR resolves #1982 #2006 #1578 

### How was it solved?
- Track biometrics enabled by adding isBiometricsEnabled field to the account redux 
- Make api call to /auth to check if an account has a number of signatures

### How was it tested?
- Android Device
- iOS Simulator

https://github.com/LiskHQ/lisk-mobile/assets/28750984/2c58cb18-3cf0-426d-ad83-123dc6eec630

### CODE REVIEW

File: src/components/screens/disableBioAuth/index.js [hunk 1]
```diff
@@ -2,31 +2,33 @@ import React from 'react';
...
+  const confirm = async () => {
+    try {
+      await removeAccountPasswordFromKeychain(account.metadata.address);
+      const newAccount = { ...account, isBiometricsEnabled: false };
+      setAccount(newAccount);
+      setCurrentAccount(newAccount);
+      modal.close();
+      onSubmit?.();
+    } catch (error) {
+      console.log(error);
```
Comment (ClementeSerrano) [inline src/components/screens/disableBioAuth/index.js:30]: is clg the best approach? can we show a toast error alert?

File: src/hooks/useDownloadFile.js [hunk 2]
```diff
@@ -34,6 +34,10 @@ export function useDownloadFile({ data, fileName, onCompleted, onError }) {
 
   const downloadFile = useCallback(async () => {
     try {
+      // delete added isBiometricsEnabled field
+      const newData = { ...data };
+      delete newData.isBiometricsEnabled;
```
Comment (ClementeSerrano) [inline src/hooks/useDownloadFile.js:39]:
```suggestion
      const {isBiometricsEnabled, ...newData} = data;
```

File: src/modules/SendToken/hooks/useSendTokenForm.js [hunk 3]
```diff
@@ -141,6 +143,26 @@ export default function useSendTokenForm({ transaction, isTransactionSuccess, in
...
   };
 
+  const getEventDataResultError = (events) => {
+    const event = events?.find((e) => e.data?.result && e.data?.result !== 0);
+
+    if (event) {
+      return EVENT_DATA_RESULT[event.data.result];
+    }
+
+    return 'Transaction dry run failed with errors, hence aborting next step.';
```
Comment (ClementeSerrano) [inline src/modules/SendToken/hooks/useSendTokenForm.js:153]: translate through i18next?

**Review by ClementeSerrano — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
