### PR TITLE
Fix validation of minimum amount to send - Closes #1193, #1271

### LINKED ISSUE #1193: A very small amount can be sent.
### Expected behavior
If there are 9 decimal places, an error message is displayed.

### Actual behavior
We can send it.
image
https://testnet-service.lisk.com/api/v2/transactions?senderAddress=lskmw4oyhawvk9us5cm45jep7gx65b86p4mm8ubfz&height=15266832

### Steps to reproduce
1. Enter the amount up to 9 decimal places in the Amount field
2. Tap the Continue button.

### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15.2
v2.0.0-beta.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1193 and #1271 

### How was it solved?
- Used validation from lisk sdk to validate amount being sent by a user

### How was it tested?
iOS simulator

### CODE REVIEW

File: src/constants/transactions.js [hunk 1]
```diff
@@ -20,6 +20,7 @@ import txUnknownDark from '../assets/images/txDetail/tx-unknown-dark.png';
 
 export const DEFAULT_MIN_REMAINING_BALANCE = 5000000;
 export const MIN_FEE_PER_BYTE = 1000;
+export const MIN_LSK_AMOUNT_TO_SEND = 1e-9;
```
Comment (ManuGowda) [inline src/constants/transactions.js:23]:
```suggestion
```
