### PR TITLE
App crashes on signout - Closes #1174

### LINKED ISSUE #1174: App crashes on sign out
### Expected behavior
App should sign out gracefully without crash

### Actual behavior
It crashes and closes the app once the signout button is clicked

### Steps to reproduce
- Sign in to the app
- Go to settings
- Sign-out

### Which version(s) does this affect? (Environment, OS, etc...)
Android & iOS v2.0.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1174

### How was it solved?
Assigned default empty string to params taken in by the string shortener utils as the cause of the crash is due to an undefined being passed when the app clears it's cache on sign-out.

See error below:
Screenshot 2021-12-17 at 10 36 57

### How was it tested?
iOS Simulator (repeatedly signed in and signed out)

### CODE REVIEW

File: src/utilities/helpers.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const merge = (...rest) => Object.assign({}, ...rest);
  *
  * @returns {String} - the shortened string
  */
-export const stringShortener = (str, leftPadd = 10, rightPadd = 0) => {
+export const stringShortener = (str = '', leftPadd = 10, rightPadd = 0) => {
```
Comment (ManuGowda) [inline src/utilities/helpers.js:56]: if the error was due to string being undefined, shouldn't it be handled rather than empty string?

e.g 

`if(str && str.length > 15) {`

**Review by ManuGowda — APPROVED** [review]
