### PR TITLE
Bug in send maximum calculation - Closes #1127

### LINKED ISSUE #1127: Bug in Send Maximum calculation
### Expected behavior
When user selects `Send Maximum` the calculated amount should be equal to the value they get in the desktop implementation

### Actual behavior
When user selects `Send Maximum` the calculated amount is not equal to the desktop implementation of `Send Maximum`

### Steps to reproduce
On the send flow for LSK, Select `Send Maximum`, compare the value gotten with the desktop

### Which version(s) does this affect? (Environment, OS, etc...)
Latest version after adapting the send flow to new design

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1127 #1126 

### How was it solved?

- Refactored Lsk.js to functional component
- Mocked Desktop implementation of hooks to calculate transaction fees

### How was it tested?

- Tested on android and iOS SImulators
- Click send maximum, and change the transaction amount, 
- The fee re-calculates and changes

### CODE REVIEW

File: src/hooks/transactionFee/useTransactionFeeCalculation.js [hunk 1]
```diff
@@ -0,0 +1,132 @@
+/* eslint-disable max-statements */
+/* eslint-disable max-len */
+import { useEffect, useReducer } from 'react';
+import { transactions } from '@liskhq/lisk-client';
+import { actionTypes, reducer, getInitialState } from './reducer';
+import * as transactionsConstants from '../../constants/transactions';
+import { fromRawLsk, toRawLsk } from '../../utilities/conversions';
+
+export const createTransactionObject = (nonce, amount = 0, message = '') => ({
```
Comment (ManuGowda) [inline src/hooks/transactionFee/useTransactionFeeCalculation.js:9]: remove the duplicated on in lsk.js

File: src/utilities/api/lisk/transactions.test.js [hunk 2]
```diff
@@ -169,3 +169,61 @@ describe('api/transactions', () => {
...
+  });
+
+  it('Calls get transaction with id to get one transaction detail', async () => {
+    await transactions.get({
+      id: 'lskebd9zfkhz6ep9kde24u8h7uxarssxxdnru2xgw'
+    });
+    expect(apiClient.getTransactions).toBeCalledWith('lskebd9zfkhz6ep9kde24u8h7uxarssxxdnru2xgw');
+  });
+
+  it('Extracts amount for transfer type', async () => {
```
Comment (ManuGowda) [inline src/utilities/api/lisk/transactions.test.js:197]:
```suggestion
  it('should extract amount for transfer type', async () => {
```

File: src/utilities/api/lisk/transactions.test.js [hunk 3]
```diff
@@ -169,3 +169,61 @@ describe('api/transactions', () => {
...
+          recipient: {
+            address: 'lskebd9zfkhz6ep9kde24u8h7uxarssxxdnru2xgw'
+          },
+          unlockObjects: [{ amount: 10 }, { amount: 11 }, { amount: 100 }, { amount: 98 }]
+        }
+      }
+    ]);
+  });
+
+  it('Extracts amount for transfer type', async () => {
```
Comment (ManuGowda) [inline src/utilities/api/lisk/transactions.test.js:223]:
```suggestion
  it('should extract amount for transfer type', async () => {
```

File: src/utilities/api/lisk/transactions.test.js [hunk 4]
```diff
@@ -169,3 +169,61 @@ describe('api/transactions', () => {
...
+          amount: '100000',
+          recipient: {
+            address: 'lskebd9zfkhz6ep9kde24u8h7uxarssxxdnru2xgw'
+          }
+        }
+      }
+    ]);
+  });
+
+  it('Calls get transaction with id to get one transaction detail', async () => {
```
Comment (ManuGowda) [inline src/utilities/api/lisk/transactions.test.js:190]:
```suggestion
  it('should call get transaction with id to get one transaction detail', async () => {
```

**Review by ManuGowda — COMMENTED** [review]
@Balanced02 all the `should` must be in lower case, please change them to lower cases 🙏🏼

**Review by ManuGowda — APPROVED** [review]

**Comment by ManuGowda** [comment]
Cross verified the fee on mobile and desktop 

desktop: https://testnet.liskscan.com/transaction/26be9bc7be8015f86ce9d0f31394c497edba0f88686ba976e2d9ac406f0d9639

mobile:https://testnet.liskscan.com/transaction/7f9b2f5e0e62e817dd3d2a40e0fd320ed0153ec31ca77d6de1f701cccba859bd
