### PR TITLE
Fix lisk application and token issues

### LINKED ISSUE #1781: Application and token Issues
### Expected behavior
- Placeholder on all inputs should be visible throughout the app
- avatar should be visible on input adornment
- switch button should work as expected
- shows error on send screen intermittently
- Show lisk application on application select screen

### Actual behavior
- [ ] Input placeholder on dark mode not visible
- [ ] Avatar not visible on dark mode
- [ ] Switch button to accept terms on create account not working
- [ ] Error appears on send screen even when there's data
- [ ] Ignore lisk on explorer screen only

### Which version(s) does this affect? (Environment, OS, etc...)
- v3.0.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?

This PR resolves #1781 

### How was it solved?

- [x] Placeholder on all inputs should be visible throughout the app
- [x] Avatar should be visible on input adornment
- [x] Switch button should work as expected
- [x] Shows error on send screen intermittently
- [x] Show lisk application on application select screen

### How was it tested?
iOS Simulator and android device

### CODE REVIEW

File: src/modules/BlockchainApplication/components/AddApplication/index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { useApplicationsExplorer } from '../../hooks/useApplicationsExplorer';
 import getAddApplicationStyles from './styles';
 
 const AddApplication = ({ navigation, t }) => {
-  const applications = useApplicationsExplorer('manage');
+  const applications = useApplicationsExplorer();
```
Comment (ClementeSerrano) [inline src/modules/BlockchainApplication/components/AddApplication/index.js:14]: on `AddApplication`, we should import applications from manage mode. Why is being removed?

File: src/modules/BlockchainApplication/components/ApplicationsExplorer/index.js [hunk 2]
```diff
@@ -57,7 +57,7 @@ export default function ApplicationsExplorer() {
   const [scannedUri, setScannedUri] = useState('');
   const tabBarHeight = useBottomTabBarHeight();
 
-  const applications = useApplicationsExplorer();
+  const applications = useApplicationsExplorer('explore');
```
Comment (ClementeSerrano) [inline src/modules/BlockchainApplication/components/ApplicationsExplorer/index.js:60]: no need to pass. By default goes to explore

File: src/modules/BlockchainApplication/hooks/useApplicationsExplorer.js [hunk 3]
```diff
@@ -7,7 +7,7 @@ import { isMainchainApplication, transformApplicationsMetaQueryResult } from '..
  * @param {'explore' | 'manage'} mode - Mode in which the apps exploring is consumed by the user. For 'explore', all apps are returned including onchain and offchain data. For 'manage', only off-chain data is returned and unregistered apps are excluded. Default: 'explore'
  * @returns {QueryResult<Array<Application>>} Available blockchain applications for users exploring.
  */
-export function useApplicationsExplorer(mode = 'explore') {
+export function useApplicationsExplorer(mode = 'manage') {
```
Comment (ClementeSerrano) [inline src/modules/BlockchainApplication/hooks/useApplicationsExplorer.js:10]: i think is more semantic to pass by default the `explorer` mode, since the hook name is "explorer". Why the need of changing it?

**Review by ClementeSerrano — CHANGES_REQUESTED** [review]

**Review by ManuGowda — APPROVED** [review]

**Review by ClementeSerrano — APPROVED** [review]
