### PR TITLE
About Lisk: Lisk Website link leads to Lisk Github - Closes #927

### LINKED ISSUE #927: About Lisk: Lisk Website link leads to Lisk Github
### How to reproduce
1. Settings -> About Lisk
1. Click read more on Lisk website link

### Actual behaviour
Lisk Github

### Expected behaviour
Lisk Website

### PR DESCRIPTION
**Pull request by colado**
# What was the bug or feature?
Described in #927.

### How did I fix it?
Corrected URL.

## Type of change
- Enhancement (a non-breaking change which adds functionality)

### How to test it?
Settings > About > Read more on the Lisk website

# Checklist:
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/components/screens/about/index.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ import getStyles from './styles';
 const logoSize = 83;
 
 const openLiskWebsite = () => {
-  Linking.openURL('https://lisk.io/products')
+  Linking.openURL('https://lisk.io/')
```
Comment (osvaldovega) [inline src/components/screens/about/index.js]: Great @colado but will be great if this URL come from a constants file, if you can do it in that way even better.

Comment (colado) [reply src/components/screens/about/index.js]: Thank you for the suggestion, @osvaldovega. I've moved this and the rest of the URLs in the project to the `constants` folder.
