### PR TITLE
Rendering modal improvements - Closes #1512 

### LINKED ISSUE #1512: Rendering modal improvements
### Expected behavior
- Modal should slide from below on mount
- Background opacity should animate

### Steps to reproduce
Open any modal eg. Account Management

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?

This PR resolves #1512 

### How was it solved?

- [x] Improved stylings of modal
- [x] Added animation type to modal
- [x] Used Animated to animate background opacity of backdrop

### How was it tested?
iOS Simulator

### CODE REVIEW

File: src/components/shared/BottomModal/index.js [hunk 1]
```diff
@@ -1,31 +1,56 @@
...
+  useEffect(() => {
+    if (show) {
+      Animated.spring(animation, {
+        toValue: 1,
+        duration: 1000,
+        delay: 50,
+      }).start();
+    }
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [show]);
```
Comment (ClementeSerrano) [inline src/components/shared/BottomModal/index.js:27]: why not to include `Animated.spring` as dep?
