### PR TITLE
Fix Socket IO not establishing connection

### LINKED ISSUE #1971: Socket IO not establishing connection
### Expected behavior

Connecting to blockchain applications WS endpoints should work properly.

This is particularly important for listening for `new.transactions` events and update the cache.

### Actual behavior

The app is not being able to establish connections via `socket.io-client`, which causes that new transactions are not received and cache don't updates properly.

### Steps to reproduce
1. Add a `connection_error` listener to the ws initialisation (`io(URL, [options])`). As example, you can just do on `src/App.js`:

```js
export default function App() {
  useEffect(() => {
    const socket = io('wss://betanet-service.lisk.com/blockchain', {
      transports: ['websocket'],
    });

    socket.on('connect_error', (error) => {
      console.log('Connection Error: ', error);
      console.log('Error msg: ', error.message);
    });

    socket.on('connect', () => {
      console.log('WebSocket client connected');
    });

    socket.on('error', (error) => {
      console.error('WebSocket error:', error);
    });

    socket.on('disconnect', (reason) => {
      console.log('WebSocket client disconnected:', reason);
    });

    socket.on('message', (data) => {
      console.log('WebSocket message:', data);
    });
  }, []);

  return (
    <View>
      <Text>Hello world</Text>
    </View>
  );
```

2. See the terminal:

Screenshot 2023-08-07 at 13 59 54

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

### PR DESCRIPTION
**Pull request by ClementeSerrano**
### What was the problem?

This PR resolves #1971 and #1890

### How was it solved?

- [x] Remove the option `{transports: ['websocket']}` from socket.io initialisation.
- [x] Patch transaction fees calculation.
- [x] Add `ios-dev` script to run iOS on devmode.
- [x] Checked that not-account-related `new.transactions` events are not updating the current logged in account:

https://github.com/LiskHQ/lisk-mobile/assets/9727036/eb1a5c18-f9d6-4d52-8262-45f90afbc19c

### How was it tested?
- [x] iOS Simulator:

https://github.com/LiskHQ/lisk-mobile/assets/9727036/d20a5926-75d1-4bd7-ba3a-286dcf491bc6

- [x] Android Emulator:

https://github.com/LiskHQ/lisk-mobile/assets/9727036/def0177c-7431-4afb-b694-ff8a5e8c461f

### CODE REVIEW

File: src/modules/Transactions/utils/Transaction.js [hunk 1]
```diff
@@ -213,9 +213,7 @@ export class Transaction {
     this.dynamicFeeEstimates = dynamicFeeEstimates;
 
     const priorityFee = this._getPriorityFee();
-    const baseFee = priorityFee > this.minFee ? priorityFee : this.minFee;
-
-    const fee = baseFee + this.extraCommandFee;
+    const fee = priorityFee > this.minFee ? priorityFee : this.minFee;
```
Comment (ManuGowda) [inline src/modules/Transactions/utils/Transaction.js:216]: 🤔 is this correct? ideally if there is priority then user need to choose it and it will be higher than min fee?

File: src/utilities/api/APIClient.js [hunk 2]
```diff
@@ -34,7 +34,7 @@ export class APIClient {
   }
 
   create({ http, ws } = {}) {
-    this.ws = io(`${ws}/blockchain`, { transports: ['websocket'] });
```
Comment (ManuGowda) [inline src/utilities/api/APIClient.js:37]: I think the deeper issue was not this? because if it was an issue it shouldn't have worked in the past? also it should fail for desktop as well.. this is more related to either CORS or the connection handling itself..

maybe we should look for the actual issue.. for time being this is ok.. but we should find the actual issue, else we might have other issues.

File: src/modules/Transactions/utils/Transaction.js (hunk 1 above)
Comment (ClementeSerrano) [reply src/modules/Transactions/utils/Transaction.js:216]: the priority fee is setup when the user selects different priorities. That is already being handled

**Review by ManuGowda — APPROVED** [review]
