### PR TITLE
Transaction History more loading fix - Closes #1179 #1171 #1186 

### LINKED ISSUE #1179: Transaction history only up 10 transactions
### Expected behavior
The transaction history should show all the txs (with a load more button or smth similar)
### Actual behavior
Transaction history shows only up 10 latest transactions
### Steps to reproduce
Log in to an account that has more then 10 transactions, check the transaction history.
### Which version(s) does this affect? (Environment, OS, etc...)
iOS 15, lisk mobile 2.0.0

### PR DESCRIPTION
**Pull request by Balanced02**
### What was the problem?
This PR resolves #1179 #1171 #1186 

### How was it solved?
- Fixed scroll listening on home screen and fix scroll issue on wallet screen
- Added title for priority message modal
- Fixed failing test by creating mock for setImmediate

### How was it tested?
Android and iOS simulators

### CODE REVIEW

File: src/components/screens/tabs/send/amount/message/index.js [hunk 1]
```diff
@@ -78,7 +77,7 @@ const Message = ({
       ) : (
         <TouchableOpacity onPress={() => setCollapsed(false)} style={[styles.addMessage]} accessibilityLabel="open-message">
           <View style={styles.row}>
-            <TouchableOpacity style={styles.actionButton}>
+            <TouchableOpacity style={styles.actionButton} testID='open-message-input' >
```
Comment (ManuGowda) [inline src/components/screens/tabs/send/amount/message/index.js:80]: testID? please change to appropriate name.

**Review by ManuGowda — COMMENTED** [review]
The overall changes looks ok.

Functionality wise when a users scrolls to bottom of the transaction list, there is no way to go back.

When users click on home page icon, the users should see the home page.

File: src/components/screens/tabs/send/amount/message/index.js (hunk 1 above)
Comment (Balanced02) [reply src/components/screens/tabs/send/amount/message/index.js:80]: @ManuGowda This is to target the TouchableOpacity for writing tests

**Review by ManuGowda — APPROVED** [review]
